/**
 * Google Maps link with an indexable URL for the page and its content.
 */
export function googleMapsSearchUrl(query: string): string {
	const q = query.trim();
	if (!q) return "https://www.google.com/maps/";
	return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;
}

/** Demo address used for the fixed map query. */
export const REGISTRY_DEMO_OFFICE_ADDRESS = "Al. Jerozolimskie 123, 00-001 Warszawa";

/**
 * Temporary Google Maps iframe for the Palace of Culture in Warsaw.
 * In production, replace the src with an embed generated by Google Maps or CMS.
 */
export const REGISTRY_DEMO_GOOGLE_MAP_EMBED =
	"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d97716.27777367992!2d20.9185968!3d52.2297716!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x471eccf6699361fe%3A0xb975570335e7cb94!2sPa%C5%82ac%20Kultury%20i%20Nauki!5e0!3m2!1spl!2spl!4v1735689600000!5m2!1spl!2spl";
